# Imagem base do Node
FROM node:22

# Define o diretório dentro do container
WORKDIR /app

# Copia package.json e instala dependências
COPY package*.json ./
RUN npm install -g @angular/cli
RUN npm install

# Copia o restante do código
COPY . .

# Porta padrão do Angular
EXPOSE 4200

# Comando para rodar o servidor de desenvolvimento
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200"]